// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3gAik4JGTuyQd__2pcYWuUdjWeUn5T0A',
    appId: '1:801662079097:web:1c0d0ca14b55033e0584a8',
    messagingSenderId: '801662079097',
    projectId: 'food-delivery-14022024',
    authDomain: 'food-delivery-14022024.firebaseapp.com',
    storageBucket: 'food-delivery-14022024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx025ge-_c4uESjlCwvlgpWUtrRK4O4gY',
    appId: '1:801662079097:android:6713e47f2b43c4190584a8',
    messagingSenderId: '801662079097',
    projectId: 'food-delivery-14022024',
    storageBucket: 'food-delivery-14022024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzxtpx6m2M-WoPpTYm60kL9RPuqkp7ots',
    appId: '1:801662079097:ios:4853d4c08396466a0584a8',
    messagingSenderId: '801662079097',
    projectId: 'food-delivery-14022024',
    storageBucket: 'food-delivery-14022024.appspot.com',
    iosBundleId: 'com.phucnguyen.foodDelivery',
  );
}
